import type { MediaItem } from '../types/movie'

export const mockMovies: MediaItem[] = [
  {
    id: 1,
    title: 'Beyond Earth',
    poster_path: '/poster1.jpg',
    backdrop_path: '/backdrop1.jpg',
    vote_average: 7.8,
    release_date: '2019-03-15',
    first_air_date: '',
    media_type: 'movie',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    genre_ids: [878, 12],
  },
  {
    id: 2,
    title: 'Bottom Gear',
    poster_path: '/poster2.jpg',
    backdrop_path: '/backdrop2.jpg',
    vote_average: 6.9,
    release_date: '2021-07-22',
    first_air_date: '',
    media_type: 'movie',
    overview: 'A street racer crosses paths with a federal agent and is forced to work for him.',
    genre_ids: [28, 80],
  },
  {
    id: 3,
    title: 'Undiscovered Cities',
    poster_path: '/poster3.jpg',
    backdrop_path: '/backdrop3.jpg',
    vote_average: 8.2,
    release_date: '',
    first_air_date: '2019-01-10',
    media_type: 'tv',
    overview: 'A documentary series exploring the hidden corners of the world\'s most fascinating cities.',
    genre_ids: [99],
  },
  {
    id: 4,
    title: '1998',
    poster_path: '/poster4.jpg',
    backdrop_path: '/backdrop4.jpg',
    vote_average: 7.1,
    release_date: '2021-11-05',
    first_air_date: '',
    media_type: 'movie',
    overview: 'A coming-of-age story set against the backdrop of a changing world.',
    genre_ids: [18, 10749],
  },
  {
    id: 5,
    title: 'Dark Side of the Moon',
    poster_path: '/poster5.jpg',
    backdrop_path: '/backdrop5.jpg',
    vote_average: 8.5,
    release_date: '',
    first_air_date: '2018-06-20',
    media_type: 'tv',
    overview: 'A psychological thriller that follows a detective investigating a series of mysterious events.',
    genre_ids: [80, 18],
  },
  {
    id: 6,
    title: 'The Great Lands',
    poster_path: '/poster6.jpg',
    backdrop_path: '/backdrop6.jpg',
    vote_average: 7.4,
    release_date: '2019-09-12',
    first_air_date: '',
    media_type: 'movie',
    overview: 'An epic journey across uncharted territories in search of a legendary land.',
    genre_ids: [12, 14],
  },
  {
    id: 7,
    title: 'The Diary',
    poster_path: '/poster7.jpg',
    backdrop_path: '/backdrop7.jpg',
    vote_average: 7.9,
    release_date: '',
    first_air_date: '2019-04-18',
    media_type: 'tv',
    overview: 'A young woman\'s diary reveals secrets that change the lives of everyone around her.',
    genre_ids: [18, 10765],
  },
  {
    id: 8,
    title: "Earth's Untouched",
    poster_path: '/poster8.jpg',
    backdrop_path: '/backdrop8.jpg',
    vote_average: 8.0,
    release_date: '2017-12-01',
    first_air_date: '',
    media_type: 'movie',
    overview: 'A breathtaking documentary showcasing the world\'s most pristine natural wonders.',
    genre_ids: [99],
  },
]
